export type ExamStream = 'Engineering' | 'Medical' | 'Management' | 'Law' | 'Design' | 'Science' | 'Agriculture' | 'PG Engineering';

export interface Exam {
  id: string;
  name: string;
  fullName: string;
  stream: ExamStream;
  conductingBody: string;
  eligibility: string;
  applicationPeriod: string;
  examPeriod: string;
  resultPeriod: string;
  examFee: string;
  mode: string;
  duration: string;
  totalMarks: number;
  totalQuestions: number | string;
  description: string;
  topColleges: string[];
  officialWebsite: string;
  difficulty: 'Moderate' | 'High' | 'Very High';
  appearingStudents: string;
}

export const exams: Exam[] = [
  // ─── Engineering ──────────────────────────────────────────────────────────
  {
    id: 'jee-main',
    name: 'JEE Main',
    fullName: 'Joint Entrance Examination — Main',
    stream: 'Engineering',
    conductingBody: 'National Testing Agency (NTA)',
    eligibility: 'Class 12 with Physics, Chemistry, Maths. 75% marks (65% for SC/ST). Age limit: no upper limit.',
    applicationPeriod: 'Nov–Dec (Session 1), Feb–Mar (Session 2)',
    examPeriod: 'Jan (Session 1), Apr (Session 2)',
    resultPeriod: 'Feb (S1), Apr–May (S2)',
    examFee: '₹1,000 (General) · ₹500 (SC/ST/PwD/Female)',
    mode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    totalMarks: 300,
    totalQuestions: 90,
    description: 'JEE Main is the gateway to NITs, IIITs, and GFTIs. Also qualifies candidates for JEE Advanced (IITs). Conducted twice a year; best score considered for ranking.',
    topColleges: ['NIT Trichy', 'NIT Warangal', 'NIT Surathkal', 'IIIT Hyderabad', 'DTU Delhi', 'BITS Pilani (via BITSAT)'],
    officialWebsite: 'https://jeemain.nta.ac.in',
    difficulty: 'High',
    appearingStudents: '12–14 lakh',
  },
  {
    id: 'jee-advanced',
    name: 'JEE Advanced',
    fullName: 'Joint Entrance Examination — Advanced',
    stream: 'Engineering',
    conductingBody: 'IIT (rotates annually)',
    eligibility: 'Top 2.5 lakh JEE Main qualifiers. Class 12 with 75% marks. Max 2 attempts.',
    applicationPeriod: 'April–May',
    examPeriod: 'May–June',
    resultPeriod: 'June',
    examFee: '₹3,200 (General) · ₹1,600 (Female/SC/ST/PwD)',
    mode: 'Computer Based Test (CBT)',
    duration: '3 hours × 2 papers',
    totalMarks: 360,
    totalQuestions: 54,
    description: 'JEE Advanced is the most competitive engineering exam in India, for admission to 23 IITs. Known for its conceptual and analytical questions requiring deep understanding.',
    topColleges: ['IIT Bombay', 'IIT Delhi', 'IIT Madras', 'IIT Kanpur', 'IIT Kharagpur', 'IIT Roorkee'],
    officialWebsite: 'https://jeeadv.ac.in',
    difficulty: 'Very High',
    appearingStudents: '1.5–2 lakh',
  },
  {
    id: 'bitsat',
    name: 'BITSAT',
    fullName: 'BITS Admission Test',
    stream: 'Engineering',
    conductingBody: 'BITS Pilani',
    eligibility: 'Class 12 with PCM, minimum 75% aggregate and 60% in each subject.',
    applicationPeriod: 'Jan–Mar',
    examPeriod: 'May–June',
    resultPeriod: 'June–July',
    examFee: '₹3,400 (Male) · ₹2,900 (Female)',
    mode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    totalMarks: 390,
    totalQuestions: 130,
    description: 'BITSAT is the entrance test for BITS Pilani, Goa, and Hyderabad campuses — top-tier private engineering colleges with excellent placement records.',
    topColleges: ['BITS Pilani', 'BITS Goa', 'BITS Hyderabad'],
    officialWebsite: 'https://www.bitsadmission.com',
    difficulty: 'High',
    appearingStudents: '3.5–4 lakh',
  },
  {
    id: 'viteee',
    name: 'VITEEE',
    fullName: 'VIT Engineering Entrance Examination',
    stream: 'Engineering',
    conductingBody: 'VIT University',
    eligibility: 'Class 12 with PCM/PCB, minimum 60% aggregate.',
    applicationPeriod: 'Nov–Feb',
    examPeriod: 'April',
    resultPeriod: 'April–May',
    examFee: '₹1,350',
    mode: 'Computer Based Test (CBT)',
    duration: '2.5 hours',
    totalMarks: 125,
    totalQuestions: 125,
    description: 'VITEEE is the entrance exam for VIT Vellore, Chennai, Bhopal, and AP campuses — one of India\'s largest private university groups with 30,000+ seats.',
    topColleges: ['VIT Vellore', 'VIT Chennai', 'VIT Bhopal', 'VIT AP'],
    officialWebsite: 'https://viteee.vit.ac.in',
    difficulty: 'Moderate',
    appearingStudents: '2–2.5 lakh',
  },
  {
    id: 'mhtcet',
    name: 'MHT CET',
    fullName: 'Maharashtra Common Entrance Test',
    stream: 'Engineering',
    conductingBody: 'State CET Cell, Maharashtra',
    eligibility: 'Class 12 with PCM, Maharashtra domicile preferred.',
    applicationPeriod: 'Jan–Mar',
    examPeriod: 'Apr–May',
    resultPeriod: 'June',
    examFee: '₹800 (General) · ₹600 (Reserved)',
    mode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    totalMarks: 200,
    totalQuestions: 150,
    description: 'MHT CET is mandatory for engineering admissions in Maharashtra government and private colleges. Scores are also accepted by some out-of-state institutes.',
    topColleges: ['VJTI Mumbai', 'COEP Pune', 'ICT Mumbai', 'Walchand College Sangli'],
    officialWebsite: 'https://cetcell.mahacet.org',
    difficulty: 'Moderate',
    appearingStudents: '4–5 lakh',
  },
  // ─── Medical ───────────────────────────────────────────────────────────────
  {
    id: 'neet-ug',
    name: 'NEET UG',
    fullName: 'National Eligibility cum Entrance Test — Undergraduate',
    stream: 'Medical',
    conductingBody: 'National Testing Agency (NTA)',
    eligibility: 'Class 12 with Physics, Chemistry, Biology. Min 50% marks (40% for SC/ST/OBC). Age 17+.',
    applicationPeriod: 'Feb–Mar',
    examPeriod: 'May',
    resultPeriod: 'June',
    examFee: '₹1,700 (General) · ₹1,000 (SC/ST/PwD)',
    mode: 'Pen & Paper (OMR)',
    duration: '3 hours 20 minutes',
    totalMarks: 720,
    totalQuestions: 180,
    description: 'NEET UG is the single national entrance exam for all MBBS, BDS, BAMS, BHMS, and BSc Nursing seats in India. Mandatory for government and private medical colleges.',
    topColleges: ['AIIMS Delhi', 'JIPMER Puducherry', 'CMC Vellore', 'KGMU Lucknow', 'Maulana Azad Medical College', 'Grant Medical College'],
    officialWebsite: 'https://neet.nta.nic.in',
    difficulty: 'Very High',
    appearingStudents: '20–22 lakh',
  },
  {
    id: 'neet-pg',
    name: 'NEET PG',
    fullName: 'National Eligibility cum Entrance Test — Postgraduate',
    stream: 'Medical',
    conductingBody: 'National Board of Examinations (NBE)',
    eligibility: 'MBBS degree with 1-year internship completed.',
    applicationPeriod: 'Jan–Feb',
    examPeriod: 'March',
    resultPeriod: 'April',
    examFee: '₹4,250',
    mode: 'Computer Based Test (CBT)',
    duration: '3 hours 30 minutes',
    totalMarks: 1200,
    totalQuestions: 200,
    description: 'NEET PG is the entrance test for MD/MS/PG Diploma admissions in government and private medical colleges. Scores are used by most states for counselling.',
    topColleges: ['AIIMS Delhi', 'PGI Chandigarh', 'JIPMER', 'CMC Vellore', 'Maulana Azad', 'KGMU'],
    officialWebsite: 'https://natboard.edu.in',
    difficulty: 'Very High',
    appearingStudents: '1.5–2 lakh',
  },
  // ─── Management ────────────────────────────────────────────────────────────
  {
    id: 'cat',
    name: 'CAT',
    fullName: 'Common Admission Test',
    stream: 'Management',
    conductingBody: 'IIM (rotates annually)',
    eligibility: 'Bachelor\'s degree with 50% marks (45% for SC/ST/PwD). Final year students eligible.',
    applicationPeriod: 'Aug–Sep',
    examPeriod: 'November',
    resultPeriod: 'January',
    examFee: '₹2,400 (General) · ₹1,200 (SC/ST/PwD)',
    mode: 'Computer Based Test (CBT)',
    duration: '2 hours',
    totalMarks: 198,
    totalQuestions: 66,
    description: 'CAT is the premier MBA entrance exam in India, required for all IIMs and 1,000+ other B-schools. Tests Verbal Ability, Data Interpretation & LR, and Quantitative Aptitude.',
    topColleges: ['IIM Ahmedabad', 'IIM Bangalore', 'IIM Calcutta', 'IIM Lucknow', 'IIM Kozhikode', 'IIM Indore', 'FMS Delhi'],
    officialWebsite: 'https://iimcat.ac.in',
    difficulty: 'Very High',
    appearingStudents: '3–3.5 lakh',
  },
  {
    id: 'xat',
    name: 'XAT',
    fullName: 'Xavier Aptitude Test',
    stream: 'Management',
    conductingBody: 'XLRI Jamshedpur',
    eligibility: 'Bachelor\'s degree in any discipline.',
    applicationPeriod: 'Aug–Nov',
    examPeriod: 'January',
    resultPeriod: 'January–February',
    examFee: '₹2,100',
    mode: 'Computer Based Test (CBT)',
    duration: '3 hours 10 minutes',
    totalMarks: 100,
    totalQuestions: 101,
    description: 'XAT is conducted by XLRI and accepted by 150+ B-schools. Unique for its Decision Making section and Essay writing, testing analytical skills and ethical reasoning.',
    topColleges: ['XLRI Jamshedpur', 'XIMB Bhubaneswar', 'IMT Ghaziabad', 'TAPMI Manipal', 'GIM Goa', 'LIBA Chennai'],
    officialWebsite: 'https://xatonline.in',
    difficulty: 'High',
    appearingStudents: '1–1.2 lakh',
  },
  {
    id: 'mat',
    name: 'MAT',
    fullName: 'Management Aptitude Test',
    stream: 'Management',
    conductingBody: 'All India Management Association (AIMA)',
    eligibility: 'Bachelor\'s degree in any discipline.',
    applicationPeriod: 'Quarterly (4 times a year)',
    examPeriod: 'Feb, May, Sep, Dec',
    resultPeriod: '3–4 weeks after exam',
    examFee: '₹1,550 (PBT) · ₹1,650 (CBT)',
    mode: 'Paper Based / CBT / Remote Proctored',
    duration: '2.5 hours',
    totalMarks: 200,
    totalQuestions: 200,
    description: 'MAT is conducted 4 times a year and accepted by 600+ B-schools. It tests Language Comprehension, Mathematical Skills, Data Analysis, Intelligence, and General Knowledge.',
    topColleges: ['BIMTECH', 'Jaipuria Institute', 'Alliance University', 'IPE Hyderabad'],
    officialWebsite: 'https://mat.aima.in',
    difficulty: 'Moderate',
    appearingStudents: '50,000–60,000 per session',
  },
  {
    id: 'snap',
    name: 'SNAP',
    fullName: 'Symbiosis National Aptitude Test',
    stream: 'Management',
    conductingBody: 'Symbiosis International University',
    eligibility: 'Bachelor\'s degree with 50% marks.',
    applicationPeriod: 'Aug–Nov',
    examPeriod: 'December',
    resultPeriod: 'January',
    examFee: '₹1,950 per test',
    mode: 'Computer Based Test (CBT)',
    duration: '60 minutes',
    totalMarks: 60,
    totalQuestions: 60,
    description: 'SNAP is the entrance test for all Symbiosis B-schools. Known for its short duration and high speed requirement. Conducted up to 3 times; best score considered.',
    topColleges: ['SIBM Pune', 'SCMHRD Pune', 'SIIB Pune', 'SIBM Bengaluru'],
    officialWebsite: 'https://www.snaptest.org',
    difficulty: 'Moderate',
    appearingStudents: '60,000–80,000',
  },
  // ─── Law ───────────────────────────────────────────────────────────────────
  {
    id: 'clat',
    name: 'CLAT',
    fullName: 'Common Law Admission Test',
    stream: 'Law',
    conductingBody: 'Consortium of NLUs',
    eligibility: 'Class 12 with 45% marks (40% for SC/ST). For UG. PG requires LLB with 50%.',
    applicationPeriod: 'Jan–Apr',
    examPeriod: 'May',
    resultPeriod: 'June',
    examFee: '₹4,000 (General) · ₹3,500 (SC/ST/PwD/BPL)',
    mode: 'Offline (Pen & Paper)',
    duration: '2 hours',
    totalMarks: 120,
    totalQuestions: 120,
    description: 'CLAT is the common entrance test for 24 National Law Universities in India. Tests English, GK & Current Affairs, Legal Reasoning, Logical Reasoning, and Quantitative Techniques.',
    topColleges: ['NLSIU Bangalore', 'NALSAR Hyderabad', 'NUJS Kolkata', 'NLU Delhi', 'NLU Jodhpur', 'GNLU Gandhinagar'],
    officialWebsite: 'https://consortiumofnlus.ac.in',
    difficulty: 'High',
    appearingStudents: '70,000–80,000',
  },
  {
    id: 'ailet',
    name: 'AILET',
    fullName: 'All India Law Entrance Test',
    stream: 'Law',
    conductingBody: 'National Law University Delhi (NLUD)',
    eligibility: 'Class 12 with 50% marks (45% for SC/ST). Age below 20 (22 for SC/ST).',
    applicationPeriod: 'Jan–Apr',
    examPeriod: 'May',
    resultPeriod: 'June',
    examFee: '₹3,000',
    mode: 'Offline (Pen & Paper)',
    duration: '1 hour 30 minutes',
    totalMarks: 150,
    totalQuestions: 150,
    description: 'AILET is the entrance exam exclusively for NLU Delhi, consistently ranked among India\'s top 3 law schools. Among the most competitive law exams in India.',
    topColleges: ['NLU Delhi (NLUD)'],
    officialWebsite: 'https://nludelhi.ac.in',
    difficulty: 'Very High',
    appearingStudents: '25,000–30,000',
  },
  // ─── Design ────────────────────────────────────────────────────────────────
  {
    id: 'nid-dat',
    name: 'NID DAT',
    fullName: 'National Institute of Design — Design Aptitude Test',
    stream: 'Design',
    conductingBody: 'National Institute of Design (NID)',
    eligibility: 'Class 12 (any stream) for BDes. Bachelor\'s degree for MDes.',
    applicationPeriod: 'Oct–Nov',
    examPeriod: 'Jan (Prelims), Mar (Mains)',
    resultPeriod: 'Feb (Prelims), Apr (Mains)',
    examFee: '₹3,000 (General) · ₹1,500 (SC/ST/PwD)',
    mode: 'Offline (Pen & Paper)',
    duration: '3 hours',
    totalMarks: 100,
    totalQuestions: 'Varies',
    description: 'NID DAT tests creative aptitude, observation, visualization, and design thinking. Consists of Prelims and Mains. Selection involves studio test and personal interview.',
    topColleges: ['NID Ahmedabad', 'NID Bengaluru', 'NID Delhi', 'NID Andhra Pradesh'],
    officialWebsite: 'https://admissions.nid.edu',
    difficulty: 'High',
    appearingStudents: '8,000–10,000',
  },
  {
    id: 'nift-entrance',
    name: 'NIFT Entrance',
    fullName: 'National Institute of Fashion Technology Entrance Exam',
    stream: 'Design',
    conductingBody: 'National Institute of Fashion Technology (NIFT)',
    eligibility: 'Class 12 (any stream) for UG courses. Graduation for PG.',
    applicationPeriod: 'Oct–Dec',
    examPeriod: 'January',
    resultPeriod: 'Feb–Mar',
    examFee: '₹2,000 (General) · ₹1,000 (SC/ST)',
    mode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    totalMarks: 100,
    totalQuestions: 100,
    description: 'NIFT Entrance test is for admission to 17 NIFT campuses across India. Tests creative ability, situation test, and group discussion/personal interview rounds.',
    topColleges: ['NIFT Delhi', 'NIFT Mumbai', 'NIFT Bengaluru', 'NIFT Chennai', 'NIFT Kolkata'],
    officialWebsite: 'https://nift.ac.in',
    difficulty: 'Moderate',
    appearingStudents: '50,000–70,000',
  },
  {
    id: 'ceed',
    name: 'CEED',
    fullName: 'Common Entrance Exam for Design',
    stream: 'Design',
    conductingBody: 'IIT Bombay',
    eligibility: 'Bachelor\'s degree (any discipline) or final year students.',
    applicationPeriod: 'Oct–Nov',
    examPeriod: 'January',
    resultPeriod: 'March',
    examFee: '₹3,200 (General) · ₹1,600 (SC/ST/PwD/Female)',
    mode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    totalMarks: 100,
    totalQuestions: 'Varies',
    description: 'CEED qualifies candidates for MDes/PhD at IITs, IISc, and NITs. Tests visualization, creativity, logical reasoning, and design sensitivity. Most prestigious design PG exam.',
    topColleges: ['IIT Bombay', 'IIT Delhi', 'IIT Guwahati', 'IIT Hyderabad', 'IISc Bangalore'],
    officialWebsite: 'https://ceed.iitb.ac.in',
    difficulty: 'High',
    appearingStudents: '12,000–15,000',
  },
  // ─── Science / Research ────────────────────────────────────────────────────
  {
    id: 'cuet',
    name: 'CUET UG',
    fullName: 'Common University Entrance Test — Undergraduate',
    stream: 'Science',
    conductingBody: 'National Testing Agency (NTA)',
    eligibility: 'Class 12 from any stream. Age and percentage as per university norms.',
    applicationPeriod: 'Feb–Mar',
    examPeriod: 'May–June',
    resultPeriod: 'July',
    examFee: '₹750 (up to 3 subjects) · ₹150 extra per subject',
    mode: 'Computer Based Test (CBT)',
    duration: '45 mins per subject',
    totalMarks: 200,
    totalQuestions: 50,
    description: 'CUET is mandatory for UG admissions to all Central Universities including DU, JNU, BHU, AMU. Tests domain knowledge, language skills, and general aptitude.',
    topColleges: ['Delhi University', 'JNU Delhi', 'BHU Varanasi', 'AMU Aligarh', 'Hyderabad University', 'Pondicherry University'],
    officialWebsite: 'https://cuet.samarth.ac.in',
    difficulty: 'Moderate',
    appearingStudents: '12–14 lakh',
  },
  {
    id: 'icar-aieea',
    name: 'ICAR AIEEA',
    fullName: 'ICAR All India Entrance Examination for Admission',
    stream: 'Agriculture',
    conductingBody: 'ICAR (Indian Council of Agricultural Research)',
    eligibility: 'Class 12 with PCB/PCM/Agriculture with 50% marks (45% for SC/ST).',
    applicationPeriod: 'Mar–Apr',
    examPeriod: 'June',
    resultPeriod: 'July',
    examFee: '₹1,000 (General) · ₹500 (SC/ST/PwD)',
    mode: 'Computer Based Test (CBT)',
    duration: '2.5 hours',
    totalMarks: 600,
    totalQuestions: 150,
    description: 'ICAR AIEEA is the national entrance test for BSc Agriculture and allied science admissions at SAUs, CUs, and ICAR-funded institutes across India.',
    topColleges: ['IARI New Delhi', 'PAU Ludhiana', 'TNAU Coimbatore', 'GBPUAT Pantnagar', 'UAS Bangalore'],
    officialWebsite: 'https://icar.org.in',
    difficulty: 'Moderate',
    appearingStudents: '80,000–1 lakh',
  },
  // ─── PG Engineering ────────────────────────────────────────────────────────
  {
    id: 'gate',
    name: 'GATE',
    fullName: 'Graduate Aptitude Test in Engineering',
    stream: 'PG Engineering',
    conductingBody: 'IITs + IISc (joint)',
    eligibility: 'B.E./B.Tech/B.Sc (Research)/M.Sc. Final year students eligible.',
    applicationPeriod: 'Sep–Oct',
    examPeriod: 'Feb',
    resultPeriod: 'March',
    examFee: '₹1,800 (General) · ₹900 (Female/SC/ST/PwD)',
    mode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    totalMarks: 100,
    totalQuestions: 65,
    description: 'GATE score is used for MTech admissions at IITs, NITs, and IISc, and also for PSU recruitment (BHEL, ONGC, GAIL, IOCL). Valid for 3 years. 29 subject papers.',
    topColleges: ['IIT Bombay', 'IISc Bangalore', 'IIT Delhi', 'IIT Madras', 'IIT Kanpur', 'IIT Kharagpur'],
    officialWebsite: 'https://gate.iitb.ac.in',
    difficulty: 'High',
    appearingStudents: '8–10 lakh',
  },
];

export const streamColors: Record<ExamStream, string> = {
  Engineering: 'bg-blue-100 text-blue-700',
  Medical: 'bg-red-100 text-red-700',
  Management: 'bg-purple-100 text-purple-700',
  Law: 'bg-amber-100 text-amber-700',
  Design: 'bg-pink-100 text-pink-700',
  Science: 'bg-green-100 text-green-700',
  Agriculture: 'bg-emerald-100 text-emerald-700',
  'PG Engineering': 'bg-indigo-100 text-indigo-700',
};

export const difficultyColors: Record<string, string> = {
  Moderate: 'text-yellow-600 bg-yellow-50',
  High: 'text-orange-600 bg-orange-50',
  'Very High': 'text-red-600 bg-red-50',
};
