import type { College, Review } from './types';

export const colleges: College[] = [
  {
    id: '1',
    name: 'Indian Institute of Technology Bombay',
    slug: 'iit-bombay',
    location: { city: 'Mumbai', state: 'Maharashtra' },
    type: 'Government',
    established: 1958,
    rating: 4.8,
    reviewCount: 1240,
    fees: { min: 100000, max: 250000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 220000, seats: 120 },
      { id: 'c2', name: 'M.Tech AI & ML', duration: '2 Years', fees: 180000, seats: 60 },
      { id: 'c3', name: 'B.Tech Electrical Engineering', duration: '4 Years', fees: 210000, seats: 80 },
      { id: 'c4', name: 'PhD Computer Science', duration: '4-6 Years', fees: 100000, seats: 30 },
    ],
    placements: {
      averagePackage: 24,
      highestPackage: 250,
      placementRate: 98,
      topRecruiters: ['Google', 'Microsoft', 'Goldman Sachs', 'DE Shaw', 'Apple', 'Amazon'],
    },
    overview:
      'IIT Bombay is one of the most prestigious engineering institutions in India, ranked among the top 150 universities globally. Founded in 1958, it offers cutting-edge research opportunities across engineering, science, and management disciplines.',
    accreditation: ['NAAC A++', 'NBA', 'NIRF Rank 3'],
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Indian_Institute_of_Technology_Bombay_Logo.svg/200px-Indian_Institute_of_Technology_Bombay_Logo.svg.png',
    tags: ['IIT', 'Top 10', 'Government', 'NIRF'],
  },
  {
    id: '2',
    name: 'Indian Institute of Technology Delhi',
    slug: 'iit-delhi',
    location: { city: 'New Delhi', state: 'Delhi' },
    type: 'Government',
    established: 1961,
    rating: 4.7,
    reviewCount: 1180,
    fees: { min: 100000, max: 240000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 230000, seats: 90 },
      { id: 'c2', name: 'B.Tech Mechanical Engineering', duration: '4 Years', fees: 210000, seats: 100 },
      { id: 'c3', name: 'M.Tech VLSI Design', duration: '2 Years', fees: 170000, seats: 40 },
      { id: 'c4', name: 'MBA', duration: '2 Years', fees: 240000, seats: 60 },
    ],
    placements: {
      averagePackage: 22,
      highestPackage: 210,
      placementRate: 97,
      topRecruiters: ['Microsoft', 'Amazon', 'Flipkart', 'McKinsey', 'BCG', 'Samsung'],
    },
    overview:
      'IIT Delhi is a world-class institution in the heart of India\'s capital. Known for its research excellence and industry partnerships, IIT Delhi consistently ranks among the top 5 engineering institutes in India.',
    accreditation: ['NAAC A++', 'NBA', 'NIRF Rank 2'],
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f8/Indian_Institute_of_Technology_Delhi_official_Logo.svg/200px-Indian_Institute_of_Technology_Delhi_official_Logo.svg.png',
    tags: ['IIT', 'Top 5', 'Government', 'NIRF'],
  },
  {
    id: '3',
    name: 'Indian Institute of Technology Madras',
    slug: 'iit-madras',
    location: { city: 'Chennai', state: 'Tamil Nadu' },
    type: 'Government',
    established: 1959,
    rating: 4.9,
    reviewCount: 1390,
    fees: { min: 95000, max: 245000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 225000, seats: 100 },
      { id: 'c2', name: 'B.Tech Civil Engineering', duration: '4 Years', fees: 200000, seats: 70 },
      { id: 'c3', name: 'M.Tech Data Science', duration: '2 Years', fees: 175000, seats: 50 },
      { id: 'c4', name: 'B.Sc Research Physics', duration: '4 Years', fees: 130000, seats: 30 },
    ],
    placements: {
      averagePackage: 26,
      highestPackage: 280,
      placementRate: 99,
      topRecruiters: ['Google', 'Facebook', 'NVIDIA', 'Qualcomm', 'Intel', 'Texas Instruments'],
    },
    overview:
      'IIT Madras is India\'s #1 ranked engineering institute (NIRF 2023). Set within a beautiful 600-acre campus, it is known for its interdisciplinary research and entrepreneurship ecosystem.',
    accreditation: ['NAAC A++', 'NBA', 'NIRF Rank 1'],
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/IIT_Madras_Logo.svg/200px-IIT_Madras_Logo.svg.png',
    tags: ['IIT', 'NIRF #1', 'Government', 'Top Ranked'],
  },
  {
    id: '4',
    name: 'Indian Institute of Technology Kanpur',
    slug: 'iit-kanpur',
    location: { city: 'Kanpur', state: 'Uttar Pradesh' },
    type: 'Government',
    established: 1959,
    rating: 4.7,
    reviewCount: 980,
    fees: { min: 100000, max: 240000 },
    courses: [
      { id: 'c1', name: 'B.Tech Aerospace Engineering', duration: '4 Years', fees: 215000, seats: 50 },
      { id: 'c2', name: 'B.Tech Computer Science', duration: '4 Years', fees: 225000, seats: 80 },
      { id: 'c3', name: 'M.Tech Robotics', duration: '2 Years', fees: 180000, seats: 30 },
      { id: 'c4', name: 'PhD Physics', duration: '5 Years', fees: 100000, seats: 20 },
    ],
    placements: {
      averagePackage: 21,
      highestPackage: 200,
      placementRate: 96,
      topRecruiters: ['Boeing', 'ISRO', 'Infosys', 'TCS', 'Oracle', 'Adobe'],
    },
    overview:
      'IIT Kanpur pioneered computer science education in India. It is renowned for its research culture, interdisciplinary programs, and alumni who have made global impact in academia and industry.',
    accreditation: ['NAAC A++', 'NBA', 'NIRF Rank 4'],
    image: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=IITK',
    tags: ['IIT', 'Top 10', 'Government', 'NIRF'],
  },
  {
    id: '5',
    name: 'IIT Kharagpur',
    slug: 'iit-kharagpur',
    location: { city: 'Kharagpur', state: 'West Bengal' },
    type: 'Government',
    established: 1951,
    rating: 4.6,
    reviewCount: 1100,
    fees: { min: 90000, max: 230000 },
    courses: [
      { id: 'c1', name: 'B.Tech Chemical Engineering', duration: '4 Years', fees: 200000, seats: 90 },
      { id: 'c2', name: 'B.Tech Electronics & Communication', duration: '4 Years', fees: 215000, seats: 110 },
      { id: 'c3', name: 'M.Tech Machine Learning', duration: '2 Years', fees: 170000, seats: 40 },
      { id: 'c4', name: 'MBA Business Analytics', duration: '2 Years', fees: 230000, seats: 60 },
    ],
    placements: {
      averagePackage: 19,
      highestPackage: 180,
      placementRate: 95,
      topRecruiters: ['Tata Motors', 'Reliance', 'Wipro', 'HCL', 'Bajaj Auto', 'L&T'],
    },
    overview:
      'IIT Kharagpur is the oldest IIT, established in 1951. Its massive 2100-acre campus houses one of India\'s largest libraries. It is known for its industry-oriented curriculum and diverse research programs.',
    accreditation: ['NAAC A++', 'NBA', 'NIRF Rank 5'],
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=IITKGP',
    tags: ['IIT', 'Top 10', 'Government', 'Oldest IIT'],
  },
  {
    id: '6',
    name: 'NIT Trichy',
    slug: 'nit-trichy',
    location: { city: 'Tiruchirappalli', state: 'Tamil Nadu' },
    type: 'Government',
    established: 1964,
    rating: 4.4,
    reviewCount: 820,
    fees: { min: 70000, max: 180000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 160000, seats: 120 },
      { id: 'c2', name: 'B.Tech Mechanical Engineering', duration: '4 Years', fees: 150000, seats: 140 },
      { id: 'c3', name: 'M.Tech Software Engineering', duration: '2 Years', fees: 130000, seats: 60 },
      { id: 'c4', name: 'B.Tech Production Engineering', duration: '4 Years', fees: 145000, seats: 80 },
    ],
    placements: {
      averagePackage: 14,
      highestPackage: 80,
      placementRate: 91,
      topRecruiters: ['Infosys', 'TCS', 'Cognizant', 'Accenture', 'HCL', 'Zoho'],
    },
    overview:
      'NIT Trichy is consistently ranked among the top NITs. Known for its strong placement record and vibrant campus life, it attracts students from across India through the JEE Main examination.',
    accreditation: ['NAAC A+', 'NBA', 'NIRF Rank 9'],
    image: 'https://images.unsplash.com/photo-1519452575417-564c1401ecc0?w=800&q=80',
    logo: 'https://placehold.co/200x200/2563EB/white?text=NITT',
    tags: ['NIT', 'Top NIT', 'Government', 'NIRF'],
  },
  {
    id: '7',
    name: 'NIT Warangal',
    slug: 'nit-warangal',
    location: { city: 'Warangal', state: 'Telangana' },
    type: 'Government',
    established: 1959,
    rating: 4.3,
    reviewCount: 760,
    fees: { min: 65000, max: 170000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 160000, seats: 110 },
      { id: 'c2', name: 'B.Tech Electronics Engineering', duration: '4 Years', fees: 150000, seats: 90 },
      { id: 'c3', name: 'M.Tech VLSI', duration: '2 Years', fees: 130000, seats: 30 },
      { id: 'c4', name: 'B.Tech Metallurgy', duration: '4 Years', fees: 140000, seats: 60 },
    ],
    placements: {
      averagePackage: 12,
      highestPackage: 60,
      placementRate: 88,
      topRecruiters: ['TCS', 'Wipro', 'Infosys', 'Amazon', 'Capgemini', 'BHEL'],
    },
    overview:
      'NIT Warangal, one of the oldest NITs, is known for its excellent infrastructure and placement opportunities. Located in Telangana, it serves as a regional hub for technical education.',
    accreditation: ['NAAC A', 'NBA', 'NIRF Rank 25'],
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
    logo: 'https://placehold.co/200x200/2563EB/white?text=NITW',
    tags: ['NIT', 'Government', 'NIRF'],
  },
  {
    id: '8',
    name: 'BITS Pilani',
    slug: 'bits-pilani',
    location: { city: 'Pilani', state: 'Rajasthan' },
    type: 'Deemed',
    established: 1964,
    rating: 4.5,
    reviewCount: 1050,
    fees: { min: 180000, max: 420000 },
    courses: [
      { id: 'c1', name: 'B.E. Computer Science', duration: '4 Years', fees: 390000, seats: 150 },
      { id: 'c2', name: 'B.E. Electronics & Instrumentation', duration: '4 Years', fees: 370000, seats: 80 },
      { id: 'c3', name: 'M.E. Software Systems', duration: '2 Years', fees: 280000, seats: 60 },
      { id: 'c4', name: 'B.Pharm', duration: '4 Years', fees: 330000, seats: 70 },
    ],
    placements: {
      averagePackage: 18,
      highestPackage: 150,
      placementRate: 94,
      topRecruiters: ['Goldman Sachs', 'Google', 'Microsoft', 'Morgan Stanley', 'Directi', 'Uber'],
    },
    overview:
      'BITS Pilani is one of India\'s top private engineering institutions, known for its unique dual-degree programs and Practice School model. It has strong industry linkages and alumni presence in top global companies.',
    accreditation: ['NAAC A+', 'NBA', 'NIRF Rank 26'],
    image: 'https://images.unsplash.com/photo-1588072432836-e10032774350?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=BITS',
    tags: ['BITS', 'Deemed', 'Top Private', 'NIRF'],
  },
  {
    id: '9',
    name: 'VIT Vellore',
    slug: 'vit-vellore',
    location: { city: 'Vellore', state: 'Tamil Nadu' },
    type: 'Deemed',
    established: 1984,
    rating: 4.1,
    reviewCount: 2100,
    fees: { min: 150000, max: 350000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 310000, seats: 400 },
      { id: 'c2', name: 'B.Tech Biomedical Engineering', duration: '4 Years', fees: 280000, seats: 100 },
      { id: 'c3', name: 'M.Tech Cyber Security', duration: '2 Years', fees: 220000, seats: 80 },
      { id: 'c4', name: 'MBA', duration: '2 Years', fees: 350000, seats: 150 },
    ],
    placements: {
      averagePackage: 8,
      highestPackage: 45,
      placementRate: 82,
      topRecruiters: ['Infosys', 'TCS', 'Wipro', 'Cognizant', 'Capgemini', 'Dell'],
    },
    overview:
      'VIT Vellore is one of India\'s largest private universities with over 55,000 students. Known for its modern infrastructure, international collaborations, and strong IT placement record.',
    accreditation: ['NAAC A++', 'NBA'],
    image: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80',
    logo: 'https://placehold.co/200x200/F59E0B/white?text=VIT',
    tags: ['Deemed', 'Private', 'Large University'],
  },
  {
    id: '10',
    name: 'Manipal Institute of Technology',
    slug: 'manipal-institute-of-technology',
    location: { city: 'Manipal', state: 'Karnataka' },
    type: 'Deemed',
    established: 1957,
    rating: 4.2,
    reviewCount: 1560,
    fees: { min: 200000, max: 450000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 420000, seats: 300 },
      { id: 'c2', name: 'B.Tech Mechanical Engineering', duration: '4 Years', fees: 390000, seats: 150 },
      { id: 'c3', name: 'M.Tech Data Science', duration: '2 Years', fees: 300000, seats: 60 },
      { id: 'c4', name: 'B.Tech Information Technology', duration: '4 Years', fees: 400000, seats: 200 },
    ],
    placements: {
      averagePackage: 10,
      highestPackage: 55,
      placementRate: 85,
      topRecruiters: ['Infosys', 'Accenture', 'IBM', 'HP', 'Mindtree', 'Mphasis'],
    },
    overview:
      'Manipal Institute of Technology, part of Manipal Academy of Higher Education, is known for its cosmopolitan campus and strong alumni network. It offers a vibrant student life alongside technical education.',
    accreditation: ['NAAC A++', 'NBA', 'NIRF Rank 52'],
    image: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=MIT',
    tags: ['Deemed', 'Private', 'Karnataka'],
  },
  {
    id: '11',
    name: 'SRM Institute of Science and Technology',
    slug: 'srm-institute',
    location: { city: 'Chennai', state: 'Tamil Nadu' },
    type: 'Deemed',
    established: 1985,
    rating: 3.9,
    reviewCount: 1820,
    fees: { min: 180000, max: 400000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science (AI)', duration: '4 Years', fees: 380000, seats: 500 },
      { id: 'c2', name: 'B.Tech Genetic Engineering', duration: '4 Years', fees: 320000, seats: 50 },
      { id: 'c3', name: 'MBA Digital Marketing', duration: '2 Years', fees: 400000, seats: 120 },
      { id: 'c4', name: 'B.Tech Mechatronics', duration: '4 Years', fees: 340000, seats: 80 },
    ],
    placements: {
      averagePackage: 7,
      highestPackage: 40,
      placementRate: 79,
      topRecruiters: ['TCS', 'Infosys', 'Wipro', 'Amazon', 'HCL', 'Zoho'],
    },
    overview:
      'SRM Institute is among the top private universities in India with 52,000+ students. It has strong collaborations with industries and institutions worldwide.',
    accreditation: ['NAAC A++', 'NBA'],
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
    logo: 'https://placehold.co/200x200/F59E0B/white?text=SRM',
    tags: ['Deemed', 'Private', 'Tamil Nadu'],
  },
  {
    id: '12',
    name: 'IIIT Hyderabad',
    slug: 'iiit-hyderabad',
    location: { city: 'Hyderabad', state: 'Telangana' },
    type: 'Deemed',
    established: 1998,
    rating: 4.4,
    reviewCount: 640,
    fees: { min: 200000, max: 350000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 320000, seats: 180 },
      { id: 'c2', name: 'B.Tech Electronics & Communication', duration: '4 Years', fees: 310000, seats: 60 },
      { id: 'c3', name: 'M.S. (Research) AI', duration: '2 Years', fees: 250000, seats: 40 },
      { id: 'c4', name: 'PhD CS', duration: '4-6 Years', fees: 150000, seats: 30 },
    ],
    placements: {
      averagePackage: 20,
      highestPackage: 140,
      placementRate: 95,
      topRecruiters: ['Microsoft', 'Amazon', 'Google', 'Samsung R&D', 'Qualcomm', 'Media.net'],
    },
    overview:
      'IIIT Hyderabad is a research-intensive institution known for its work in AI, NLP, and data sciences. It uniquely focuses on research from the undergraduate level.',
    accreditation: ['NAAC A', 'NBA'],
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=IIITH',
    tags: ['IIIT', 'Deemed', 'Research', 'Top Placement'],
  },
  {
    id: '13',
    name: 'Delhi University (North Campus)',
    slug: 'delhi-university',
    location: { city: 'New Delhi', state: 'Delhi' },
    type: 'Government',
    established: 1922,
    rating: 4.0,
    reviewCount: 2400,
    fees: { min: 15000, max: 80000 },
    courses: [
      { id: 'c1', name: 'B.Sc (H) Computer Science', duration: '3 Years', fees: 40000, seats: 200 },
      { id: 'c2', name: 'B.A. (H) Economics', duration: '3 Years', fees: 25000, seats: 300 },
      { id: 'c3', name: 'B.Com (H)', duration: '3 Years', fees: 20000, seats: 500 },
      { id: 'c4', name: 'M.Sc Mathematics', duration: '2 Years', fees: 30000, seats: 100 },
    ],
    placements: {
      averagePackage: 6,
      highestPackage: 30,
      placementRate: 70,
      topRecruiters: ['Deloitte', 'EY', 'KPMG', 'Bain', 'HUL', 'P&G'],
    },
    overview:
      'University of Delhi is India\'s most prestigious central university. Its 16 faculties and 86 academic departments offer programs that blend liberal arts with professional education.',
    accreditation: ['NAAC A++', 'NIRF Rank 13'],
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=DU',
    tags: ['Central University', 'Government', 'Delhi', 'Top Ranked'],
  },
  {
    id: '14',
    name: 'Anna University',
    slug: 'anna-university',
    location: { city: 'Chennai', state: 'Tamil Nadu' },
    type: 'Government',
    established: 1978,
    rating: 3.8,
    reviewCount: 1900,
    fees: { min: 50000, max: 120000 },
    courses: [
      { id: 'c1', name: 'B.E. Computer Science', duration: '4 Years', fees: 110000, seats: 240 },
      { id: 'c2', name: 'B.E. Civil Engineering', duration: '4 Years', fees: 90000, seats: 180 },
      { id: 'c3', name: 'M.E. Embedded Systems', duration: '2 Years', fees: 80000, seats: 40 },
      { id: 'c4', name: 'MBA', duration: '2 Years', fees: 120000, seats: 80 },
    ],
    placements: {
      averagePackage: 5,
      highestPackage: 28,
      placementRate: 72,
      topRecruiters: ['TCS', 'Infosys', 'Cognizant', 'L&T', 'TVS', 'Ashok Leyland'],
    },
    overview:
      'Anna University is a technical university in Tamil Nadu that affiliates hundreds of engineering colleges. Its main campus in Chennai offers quality education at affordable fees.',
    accreditation: ['NAAC A+', 'NBA', 'NIRF Rank 20'],
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80',
    logo: 'https://placehold.co/200x200/2563EB/white?text=AU',
    tags: ['Government', 'Tamil Nadu', 'Affordable'],
  },
  {
    id: '15',
    name: 'Jadavpur University',
    slug: 'jadavpur-university',
    location: { city: 'Kolkata', state: 'West Bengal' },
    type: 'Government',
    established: 1955,
    rating: 4.0,
    reviewCount: 870,
    fees: { min: 20000, max: 60000 },
    courses: [
      { id: 'c1', name: 'B.E. Computer Science', duration: '4 Years', fees: 50000, seats: 60 },
      { id: 'c2', name: 'B.E. Electrical Engineering', duration: '4 Years', fees: 45000, seats: 70 },
      { id: 'c3', name: 'M.E. Power Systems', duration: '2 Years', fees: 40000, seats: 20 },
      { id: 'c4', name: 'B.A. English', duration: '3 Years', fees: 20000, seats: 80 },
    ],
    placements: {
      averagePackage: 8,
      highestPackage: 45,
      placementRate: 78,
      topRecruiters: ['TCS', 'Wipro', 'SAIL', 'NTPC', 'Tata Steel', 'CTS'],
    },
    overview:
      'Jadavpur University is a premier state university in West Bengal with a legacy of academic excellence and social consciousness. It is highly regarded for engineering and arts disciplines.',
    accreditation: ['NAAC A+', 'NIRF Rank 14'],
    image: 'https://images.unsplash.com/photo-1519452575417-564c1401ecc0?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=JU',
    tags: ['Government', 'State University', 'West Bengal', 'Affordable'],
  },
  {
    id: '16',
    name: 'Amity University Noida',
    slug: 'amity-university-noida',
    location: { city: 'Noida', state: 'Uttar Pradesh' },
    type: 'Private',
    established: 2005,
    rating: 3.7,
    reviewCount: 3200,
    fees: { min: 200000, max: 500000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 460000, seats: 600 },
      { id: 'c2', name: 'BBA', duration: '3 Years', fees: 300000, seats: 400 },
      { id: 'c3', name: 'MBA', duration: '2 Years', fees: 500000, seats: 250 },
      { id: 'c4', name: 'B.Sc Biotechnology', duration: '3 Years', fees: 280000, seats: 100 },
    ],
    placements: {
      averagePackage: 6,
      highestPackage: 30,
      placementRate: 75,
      topRecruiters: ['Infosys', 'Wipro', 'HCL', 'Deloitte', 'ICICI Bank', 'HDFC'],
    },
    overview:
      'Amity University is a large private institution in the Delhi-NCR region offering 300+ programs. It has a modern campus, strong corporate connections, and international exchange programs.',
    accreditation: ['NAAC A+', 'NBA'],
    image: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&q=80',
    logo: 'https://placehold.co/200x200/F59E0B/white?text=Amity',
    tags: ['Private', 'UP', 'Large Campus'],
  },
  {
    id: '17',
    name: 'Symbiosis International University',
    slug: 'symbiosis-international-university',
    location: { city: 'Pune', state: 'Maharashtra' },
    type: 'Deemed',
    established: 2002,
    rating: 4.0,
    reviewCount: 1350,
    fees: { min: 180000, max: 500000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 400000, seats: 200 },
      { id: 'c2', name: 'MBA', duration: '2 Years', fees: 500000, seats: 300 },
      { id: 'c3', name: 'B.A. LLB', duration: '5 Years', fees: 380000, seats: 100 },
      { id: 'c4', name: 'B.Sc Data Science', duration: '3 Years', fees: 350000, seats: 80 },
    ],
    placements: {
      averagePackage: 9,
      highestPackage: 50,
      placementRate: 83,
      topRecruiters: ['Deloitte', 'PwC', 'EY', 'Amazon', 'Juspay', 'Cummins'],
    },
    overview:
      'Symbiosis International University is a multidisciplinary deemed university in Pune. Known for its MBA programs and strong industry ties, it attracts students from over 85 countries.',
    accreditation: ['NAAC A', 'NBA'],
    image: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=SIU',
    tags: ['Deemed', 'MBA', 'Pune', 'International'],
  },
  {
    id: '18',
    name: 'Christ University Bangalore',
    slug: 'christ-university-bangalore',
    location: { city: 'Bangalore', state: 'Karnataka' },
    type: 'Deemed',
    established: 1969,
    rating: 4.1,
    reviewCount: 1700,
    fees: { min: 100000, max: 350000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 320000, seats: 180 },
      { id: 'c2', name: 'B.Com (Finance)', duration: '3 Years', fees: 160000, seats: 300 },
      { id: 'c3', name: 'MBA', duration: '2 Years', fees: 350000, seats: 200 },
      { id: 'c4', name: 'B.Sc Psychology', duration: '3 Years', fees: 120000, seats: 120 },
    ],
    placements: {
      averagePackage: 7,
      highestPackage: 36,
      placementRate: 80,
      topRecruiters: ['Deloitte', 'Infosys', 'Accenture', 'Byju\'s', 'HDFC', 'Axis Bank'],
    },
    overview:
      'Christ University is a premier institution in Bangalore known for its holistic approach to education. It emphasizes academic excellence, social commitment, and personal development.',
    accreditation: ['NAAC A++', 'NBA'],
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    logo: 'https://placehold.co/200x200/2563EB/white?text=Christ',
    tags: ['Deemed', 'Bangalore', 'Liberal Arts'],
  },
  {
    id: '19',
    name: 'Lovely Professional University',
    slug: 'lovely-professional-university',
    location: { city: 'Phagwara', state: 'Punjab' },
    type: 'Private',
    established: 2005,
    rating: 3.5,
    reviewCount: 4500,
    fees: { min: 120000, max: 380000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 350000, seats: 1000 },
      { id: 'c2', name: 'BBA', duration: '3 Years', fees: 200000, seats: 600 },
      { id: 'c3', name: 'B.Pharm', duration: '4 Years', fees: 180000, seats: 200 },
      { id: 'c4', name: 'MBA', duration: '2 Years', fees: 380000, seats: 400 },
    ],
    placements: {
      averagePackage: 5,
      highestPackage: 25,
      placementRate: 68,
      topRecruiters: ['TCS', 'Infosys', 'Wipro', 'HCL', 'Concentrix', 'WNS'],
    },
    overview:
      'LPU is India\'s largest single-campus private university with over 30,000 students. It offers 200+ programs and is known for its diverse student community and affordable education.',
    accreditation: ['NAAC A++'],
    image: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80',
    logo: 'https://placehold.co/200x200/F59E0B/white?text=LPU',
    tags: ['Private', 'Punjab', 'Large University', 'Affordable'],
  },
  {
    id: '20',
    name: 'PSG College of Technology',
    slug: 'psg-college-of-technology',
    location: { city: 'Coimbatore', state: 'Tamil Nadu' },
    type: 'Private',
    established: 1951,
    rating: 4.2,
    reviewCount: 960,
    fees: { min: 90000, max: 200000 },
    courses: [
      { id: 'c1', name: 'B.E. Computer Science', duration: '4 Years', fees: 185000, seats: 120 },
      { id: 'c2', name: 'B.E. Mechanical Engineering', duration: '4 Years', fees: 170000, seats: 140 },
      { id: 'c3', name: 'M.E. CAD/CAM', duration: '2 Years', fees: 140000, seats: 30 },
      { id: 'c4', name: 'B.E. Electronics & Communication', duration: '4 Years', fees: 175000, seats: 100 },
    ],
    placements: {
      averagePackage: 9,
      highestPackage: 42,
      placementRate: 87,
      topRecruiters: ['TCS', 'Infosys', 'CTS', 'Robert Bosch', 'Pricol', 'Elgi Equipment'],
    },
    overview:
      'PSG College of Technology is one of Tamil Nadu\'s most reputed engineering colleges, known for its strong industry connections with Coimbatore\'s manufacturing sector and quality technical education.',
    accreditation: ['NAAC A+', 'NBA', 'NIRF Rank 59'],
    image: 'https://images.unsplash.com/photo-1519452575417-564c1401ecc0?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=PSG',
    tags: ['Private', 'Tamil Nadu', 'Engineering'],
  },
  {
    id: '21',
    name: 'NIT Surathkal',
    slug: 'nit-surathkal',
    location: { city: 'Surathkal', state: 'Karnataka' },
    type: 'Government',
    established: 1960,
    rating: 4.2,
    reviewCount: 690,
    fees: { min: 60000, max: 160000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 150000, seats: 100 },
      { id: 'c2', name: 'B.Tech Electronics Engineering', duration: '4 Years', fees: 140000, seats: 80 },
      { id: 'c3', name: 'M.Tech Information Technology', duration: '2 Years', fees: 120000, seats: 30 },
      { id: 'c4', name: 'B.Tech Mining Engineering', duration: '4 Years', fees: 130000, seats: 40 },
    ],
    placements: {
      averagePackage: 11,
      highestPackage: 52,
      placementRate: 86,
      topRecruiters: ['Amazon', 'Microsoft', 'Infosys', 'Samsung', 'DRDO', 'Bharat Electronics'],
    },
    overview:
      'NIT Surathkal (NITK) is a premier NIT located on the scenic Karnataka coast. It is known for its strong placement record in IT, core engineering, and research programs.',
    accreditation: ['NAAC A+', 'NBA', 'NIRF Rank 27'],
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80',
    logo: 'https://placehold.co/200x200/2563EB/white?text=NITK',
    tags: ['NIT', 'Government', 'Karnataka', 'NIRF'],
  },
  {
    id: '22',
    name: 'IIIT Bangalore',
    slug: 'iiit-bangalore',
    location: { city: 'Bangalore', state: 'Karnataka' },
    type: 'Deemed',
    established: 1999,
    rating: 4.3,
    reviewCount: 520,
    fees: { min: 250000, max: 450000 },
    courses: [
      { id: 'c1', name: 'B.Tech Computer Science', duration: '4 Years', fees: 420000, seats: 130 },
      { id: 'c2', name: 'M.Tech Software Engineering', duration: '2 Years', fees: 350000, seats: 80 },
      { id: 'c3', name: 'M.S. (Research) Data Science', duration: '2 Years', fees: 300000, seats: 40 },
      { id: 'c4', name: 'iMTech (Integrated) CS', duration: '5 Years', fees: 400000, seats: 60 },
    ],
    placements: {
      averagePackage: 17,
      highestPackage: 100,
      placementRate: 93,
      topRecruiters: ['Amazon', 'Flipkart', 'Visa', 'Walmart Labs', 'Oracle', 'Cisco'],
    },
    overview:
      'IIIT Bangalore is a research-driven institute known for producing top software engineers. Located in India\'s Silicon Valley, it has direct industry ties with Bangalore\'s tech ecosystem.',
    accreditation: ['NAAC A', 'NBA'],
    image: 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=IIITB',
    tags: ['IIIT', 'Deemed', 'Bangalore', 'Tech'],
  },
  {
    id: '23',
    name: 'Savitribai Phule Pune University',
    slug: 'pune-university',
    location: { city: 'Pune', state: 'Maharashtra' },
    type: 'Government',
    established: 1948,
    rating: 3.7,
    reviewCount: 1100,
    fees: { min: 20000, max: 80000 },
    courses: [
      { id: 'c1', name: 'B.E. Computer Engineering', duration: '4 Years', fees: 70000, seats: 180 },
      { id: 'c2', name: 'M.Sc Computer Science', duration: '2 Years', fees: 45000, seats: 80 },
      { id: 'c3', name: 'MBA', duration: '2 Years', fees: 80000, seats: 100 },
      { id: 'c4', name: 'B.Sc Physics', duration: '3 Years', fees: 20000, seats: 200 },
    ],
    placements: {
      averagePackage: 5,
      highestPackage: 22,
      placementRate: 65,
      topRecruiters: ['TCS', 'Infosys', 'Persistent', 'KPIT', 'Zensar', 'Cummins'],
    },
    overview:
      'Pune University, renamed after social reformer Savitribai Phule, is one of Maharashtra\'s leading universities. It affiliates 800+ colleges and offers diverse programs at affordable fees.',
    accreditation: ['NAAC A+', 'NIRF Rank 42'],
    image: 'https://images.unsplash.com/photo-1588072432836-e10032774350?w=800&q=80',
    logo: 'https://placehold.co/200x200/2563EB/white?text=SPPU',
    tags: ['Government', 'Maharashtra', 'State University', 'Affordable'],
  },
  {
    id: '24',
    name: 'Osmania University',
    slug: 'osmania-university',
    location: { city: 'Hyderabad', state: 'Telangana' },
    type: 'Government',
    established: 1918,
    rating: 3.6,
    reviewCount: 780,
    fees: { min: 15000, max: 60000 },
    courses: [
      { id: 'c1', name: 'B.E. Computer Science', duration: '4 Years', fees: 55000, seats: 120 },
      { id: 'c2', name: 'B.A. History', duration: '3 Years', fees: 15000, seats: 300 },
      { id: 'c3', name: 'M.Sc Statistics', duration: '2 Years', fees: 30000, seats: 60 },
      { id: 'c4', name: 'LLB', duration: '3 Years', fees: 25000, seats: 100 },
    ],
    placements: {
      averagePackage: 4,
      highestPackage: 18,
      placementRate: 60,
      topRecruiters: ['TCS', 'Wipro', 'BHEL', 'ONGC', 'State Bank', 'LIC'],
    },
    overview:
      'Osmania University is the seventh oldest university in India. Known for its heritage architecture and contributions to education in the Deccan region, it offers affordable quality education.',
    accreditation: ['NAAC A', 'NIRF Rank 48'],
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80',
    logo: 'https://placehold.co/200x200/1B3A6B/white?text=OU',
    tags: ['Government', 'State University', 'Telangana', 'Heritage'],
  },
  {
    id: '25',
    name: 'Thapar Institute of Engineering',
    slug: 'thapar-institute',
    location: { city: 'Patiala', state: 'Punjab' },
    type: 'Deemed',
    established: 1956,
    rating: 4.0,
    reviewCount: 840,
    fees: { min: 180000, max: 380000 },
    courses: [
      { id: 'c1', name: 'B.E. Computer Engineering', duration: '4 Years', fees: 360000, seats: 200 },
      { id: 'c2', name: 'B.E. Electrical Engineering', duration: '4 Years', fees: 340000, seats: 120 },
      { id: 'c3', name: 'M.E. Data Science', duration: '2 Years', fees: 280000, seats: 40 },
      { id: 'c4', name: 'B.E. Mechanical Engineering', duration: '4 Years', fees: 340000, seats: 150 },
    ],
    placements: {
      averagePackage: 11,
      highestPackage: 58,
      placementRate: 86,
      topRecruiters: ['Amazon', 'Infosys', 'Google', 'Maruti Suzuki', 'Seimens', 'ISRO'],
    },
    overview:
      'Thapar Institute is a premier deemed engineering university in Punjab. Its NIRF ranking and industry-oriented curriculum make it a preferred destination for students seeking quality private engineering education.',
    accreditation: ['NAAC A', 'NBA', 'NIRF Rank 35'],
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80',
    logo: 'https://placehold.co/200x200/F59E0B/white?text=TU',
    tags: ['Deemed', 'Punjab', 'Engineering', 'NIRF'],
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    collegeId: '1',
    author: 'Arjun Mehta',
    rating: 5,
    comment:
      'IIT Bombay truly changed my life. The professors are world-class, the peers are brilliant, and the research opportunities are unmatched. The campus life is vibrant with hundreds of clubs and events.',
    year: 2023,
    course: 'B.Tech Computer Science',
  },
  {
    id: 'r2',
    collegeId: '1',
    author: 'Priya Sharma',
    rating: 5,
    comment:
      'Best decision of my life. Excellent placements — I got placed at Google. The institute culture promotes innovation and entrepreneurship strongly.',
    year: 2023,
    course: 'M.Tech AI & ML',
  },
  {
    id: 'r3',
    collegeId: '1',
    author: 'Rahul Verma',
    rating: 4,
    comment:
      'Academics are very demanding but rewarding. The faculty is highly qualified. Hostel facilities are decent though a bit old in some blocks.',
    year: 2022,
    course: 'B.Tech Electrical Engineering',
  },
  {
    id: 'r4',
    collegeId: '1',
    author: 'Sneha Nair',
    rating: 5,
    comment:
      'The interdisciplinary approach at IITB is a huge advantage. I could pursue courses from management, design, and engineering simultaneously. Alumni network is phenomenal.',
    year: 2022,
    course: 'B.Tech Computer Science',
  },
  {
    id: 'r5',
    collegeId: '1',
    author: 'Karthik Reddy',
    rating: 4,
    comment:
      'Research culture is excellent. The placement season is very competitive but most students get well-paying offers. The institute has grown tremendously in recent years.',
    year: 2021,
    course: 'PhD Computer Science',
  },
  {
    id: 'r6',
    collegeId: '2',
    author: 'Amit Gupta',
    rating: 5,
    comment:
      'IIT Delhi is the gold standard. The location in Delhi gives amazing networking opportunities. Professors are leaders in their fields.',
    year: 2023,
    course: 'B.Tech Computer Science',
  },
  {
    id: 'r7',
    collegeId: '2',
    author: 'Deepika Singh',
    rating: 4,
    comment:
      'Great academic environment. Some departments are stronger than others but overall the quality is excellent. Placements are top-notch.',
    year: 2022,
    course: 'MBA',
  },
];
