export type ScholarshipCategory = 'Merit' | 'Need-Based' | 'State' | 'Minority' | 'SC/ST/OBC' | 'Sports' | 'Girl Child' | 'Differently Abled';
export type ScholarshipLevel = 'UG' | 'PG' | 'Both' | 'Doctoral';
export type ScholarshipStream = 'All' | 'Engineering' | 'Medical' | 'Management' | 'Law' | 'Arts & Humanities' | 'Science';

export interface Scholarship {
  id: string;
  name: string;
  provider: string;
  category: ScholarshipCategory;
  level: ScholarshipLevel;
  stream: ScholarshipStream;
  amount: string;
  eligibility: string;
  applicationPeriod: string;
  selectionCriteria: string;
  documentsRequired: string[];
  description: string;
  officialWebsite: string;
  renewable: boolean;
  seats?: string;
}

export const scholarships: Scholarship[] = [
  // ─── Central Government ───────────────────────────────────────────────────
  {
    id: 'pm-scholarship',
    name: 'Prime Minister Scholarship Scheme',
    provider: 'Ministry of Home Affairs, Government of India',
    category: 'Merit',
    level: 'UG',
    stream: 'All',
    amount: '₹36,000/year (Boys) · ₹30,000/year (Girls)',
    eligibility: 'Wards/widows of ex-servicemen/police. Min 60% in Class 12.',
    applicationPeriod: 'Jul–Oct (every year)',
    selectionCriteria: 'Merit in qualifying exam, family income < ₹6 LPA',
    documentsRequired: ['ESM Certificate', 'Class 12 Marksheet', 'Income Certificate', 'Domicile Certificate', 'Aadhaar Card'],
    description: 'Provides financial assistance to wards/widows of Ex-Servicemen and Ex-Coast Guard personnel for pursuing professional degree courses.',
    officialWebsite: 'https://ksb.gov.in',
    renewable: true,
    seats: '5,500 per year',
  },
  {
    id: 'national-merit-scholarship',
    name: 'National Merit Scholarship',
    provider: 'Ministry of Education, Government of India',
    category: 'Merit',
    level: 'UG',
    stream: 'All',
    amount: '₹12,000/year',
    eligibility: 'Min 80% in Class 10 from recognized board. Family income < ₹1.5 LPA.',
    applicationPeriod: 'Aug–Oct (every year)',
    selectionCriteria: 'Score in Class 10 board exam; income criterion',
    documentsRequired: ['Class 10 Marksheet', 'Income Certificate', 'Aadhaar Card', 'Bank Account Details'],
    description: 'Awarded to meritorious students from economically weaker sections to support their higher education.',
    officialWebsite: 'https://scholarships.gov.in',
    renewable: true,
  },
  {
    id: 'central-sector-scholarship',
    name: 'Central Sector Scholarship for College & University Students',
    provider: 'Ministry of Education, Government of India',
    category: 'Merit',
    level: 'UG',
    stream: 'All',
    amount: '₹12,000/year (UG) · ₹20,000/year (PG)',
    eligibility: 'Top 80th percentile in Class 12 board. Family income ≤ ₹8 LPA.',
    applicationPeriod: 'Oct–Nov (every year)',
    selectionCriteria: 'Percentile rank in board exam; income criterion',
    documentsRequired: ['Class 12 Marksheet', 'Income Certificate', 'Aadhaar', 'College Admission Proof'],
    description: 'Supports meritorious students from financially weaker sections pursuing higher education in colleges and universities.',
    officialWebsite: 'https://scholarships.gov.in',
    renewable: true,
    seats: '82,000 per year',
  },
  {
    id: 'post-matric-scholarship-sc',
    name: 'Post-Matric Scholarship for SC Students',
    provider: 'Ministry of Social Justice & Empowerment, GoI',
    category: 'SC/ST/OBC',
    level: 'Both',
    stream: 'All',
    amount: 'Full tuition fee + maintenance allowance (course-dependent)',
    eligibility: 'SC students. Family income < ₹2.5 LPA.',
    applicationPeriod: 'Jul–Dec (every year)',
    selectionCriteria: 'SC certificate; income below threshold',
    documentsRequired: ['Caste Certificate', 'Income Certificate', 'Aadhaar', 'Admission Letter', 'Bank Account'],
    description: 'Covers tuition fees and living expenses for Scheduled Caste students pursuing post-matric education.',
    officialWebsite: 'https://scholarships.gov.in',
    renewable: true,
  },
  {
    id: 'post-matric-scholarship-st',
    name: 'Post-Matric Scholarship for ST Students',
    provider: 'Ministry of Tribal Affairs, GoI',
    category: 'SC/ST/OBC',
    level: 'Both',
    stream: 'All',
    amount: 'Full tuition fee + maintenance allowance',
    eligibility: 'ST students. Family income < ₹2.5 LPA.',
    applicationPeriod: 'Jul–Dec (every year)',
    selectionCriteria: 'ST certificate; income below threshold',
    documentsRequired: ['Tribe Certificate', 'Income Certificate', 'Aadhaar', 'Admission Letter'],
    description: 'Financial support for Scheduled Tribe students to reduce dropout rates and encourage higher education.',
    officialWebsite: 'https://scholarships.gov.in',
    renewable: true,
  },
  {
    id: 'obc-scholarship',
    name: 'Post-Matric Scholarship for OBC Students',
    provider: 'Ministry of Social Justice & Empowerment, GoI',
    category: 'SC/ST/OBC',
    level: 'Both',
    stream: 'All',
    amount: 'Tuition fee reimbursement + maintenance allowance',
    eligibility: 'OBC students. Family income < ₹1 LPA.',
    applicationPeriod: 'Aug–Nov (every year)',
    selectionCriteria: 'OBC certificate; income criterion',
    documentsRequired: ['OBC Certificate', 'Income Certificate', 'Aadhaar', 'Admission Proof'],
    description: 'Aims to enable OBC students to complete their post-matric education without financial hardship.',
    officialWebsite: 'https://scholarships.gov.in',
    renewable: true,
  },
  {
    id: 'minority-scholarship',
    name: 'Post-Matric Scholarship for Minorities',
    provider: 'Ministry of Minority Affairs, GoI',
    category: 'Minority',
    level: 'Both',
    stream: 'All',
    amount: '₹7,000–₹12,000/year',
    eligibility: 'Muslim/Christian/Sikh/Buddhist/Jain/Parsi students. Family income < ₹2 LPA. Min 50% in last exam.',
    applicationPeriod: 'Aug–Oct (every year)',
    selectionCriteria: 'Minority community certificate; income criterion; merit',
    documentsRequired: ['Community Certificate', 'Income Certificate', 'Aadhaar', 'Previous Marksheet', 'Admission Proof'],
    description: 'Supports students belonging to notified minority communities to pursue higher and technical education.',
    officialWebsite: 'https://scholarships.gov.in',
    renewable: true,
    seats: '30 lakh per year',
  },
  {
    id: 'inspire-scholarship',
    name: 'INSPIRE Scholarship for Higher Education (SHE)',
    provider: 'Department of Science & Technology, GoI',
    category: 'Merit',
    level: 'UG',
    stream: 'Science',
    amount: '₹80,000/year',
    eligibility: 'Top 1% in Class 12 board or JEE/NEET top rankers pursuing BSc/BS in Natural Sciences.',
    applicationPeriod: 'Sep–Dec (every year)',
    selectionCriteria: 'Top percentile in board exam; pursuing science degree',
    documentsRequired: ['Class 12 Marksheet', 'Board Rank Certificate', 'Admission Proof', 'Aadhaar'],
    description: 'Attracts talented students to pursue natural sciences at UG level to build a critical resource base for S&T system.',
    officialWebsite: 'https://online-inspire.gov.in',
    renewable: true,
    seats: '10,000 per year',
  },
  {
    id: 'gate-scholarship',
    name: 'GATE/NET Scholarship',
    provider: 'Ministry of Education (AICTE), GoI',
    category: 'Merit',
    level: 'PG',
    stream: 'Engineering',
    amount: '₹12,400/month (M.Tech) · ₹8,000/month (M.Sc)',
    eligibility: 'Valid GATE/NET score. Enrolled in M.Tech/M.Sc at recognized institution.',
    applicationPeriod: 'At time of M.Tech/M.Sc admission',
    selectionCriteria: 'Valid GATE score (percentile-based); institution ranking',
    documentsRequired: ['GATE Scorecard', 'Admission Letter', 'Aadhaar', 'Bank Account'],
    description: 'Monthly stipend for GATE-qualified students pursuing M.Tech/M.Sc to encourage postgraduate engineering education.',
    officialWebsite: 'https://aicte-india.org',
    renewable: true,
  },
  {
    id: 'phd-fellowship-ugc',
    name: 'UGC Junior Research Fellowship (JRF)',
    provider: 'University Grants Commission (UGC)',
    category: 'Merit',
    level: 'Doctoral',
    stream: 'All',
    amount: '₹37,000/month (JRF) · ₹42,000/month (SRF)',
    eligibility: 'NET/JRF qualified. Enrolled in PhD at recognized university.',
    applicationPeriod: 'After NET/JRF result',
    selectionCriteria: 'NET/JRF score rank',
    documentsRequired: ['NET/JRF Certificate', 'Admission Letter', 'Aadhaar', 'Bank Account'],
    description: 'Fellowships for meritorious students to undertake advanced studies and research in Indian universities and colleges.',
    officialWebsite: 'https://ugc.ac.in',
    renewable: true,
  },

  // ─── State Government ─────────────────────────────────────────────────────
  {
    id: 'maharashtra-ebc',
    name: 'Maharashtra EBC Scholarship',
    provider: 'Social Welfare Department, Maharashtra',
    category: 'Need-Based',
    level: 'Both',
    stream: 'All',
    amount: '₹15,000–₹60,000/year (course-dependent)',
    eligibility: 'Economically Backward Class students. Maharashtra domicile. Family income < ₹8 LPA.',
    applicationPeriod: 'Oct–Dec (every year)',
    selectionCriteria: 'Income certificate; domicile; merit in qualifying exam',
    documentsRequired: ['EBC Certificate', 'Income Certificate', 'Domicile', 'Aadhaar', 'Admission Proof'],
    description: 'Provides financial assistance to economically backward students in Maharashtra for pursuing higher education.',
    officialWebsite: 'https://mahaeschol.maharashtra.gov.in',
    renewable: true,
  },
  {
    id: 'up-scholarship',
    name: 'UP Scholarship Scheme',
    provider: 'Social Welfare Department, Uttar Pradesh',
    category: 'SC/ST/OBC',
    level: 'Both',
    stream: 'All',
    amount: 'Full tuition fee + maintenance allowance',
    eligibility: 'SC/ST/OBC/General EWS students domiciled in UP. Income-based.',
    applicationPeriod: 'Jul–Sep (every year)',
    selectionCriteria: 'Caste certificate; income; UP domicile',
    documentsRequired: ['Caste Certificate', 'Income Certificate', 'UP Domicile', 'Aadhaar', 'Marksheet'],
    description: 'Comprehensive scholarship scheme for students from backward classes in Uttar Pradesh for pre and post matric education.',
    officialWebsite: 'https://scholarship.up.gov.in',
    renewable: true,
  },
  {
    id: 'west-bengal-swami-vivekananda',
    name: 'Swami Vivekananda Merit-cum-Means Scholarship',
    provider: 'Backward Classes Welfare Department, West Bengal',
    category: 'Need-Based',
    level: 'UG',
    stream: 'All',
    amount: '₹1,000–₹5,000/month',
    eligibility: 'Domiciled in West Bengal. Min 75% in Class 12. Family income < ₹2.5 LPA.',
    applicationPeriod: 'Oct–Nov (every year)',
    selectionCriteria: 'Merit + income criterion; WB domicile',
    documentsRequired: ['WB Domicile', 'Class 12 Marksheet', 'Income Certificate', 'Aadhaar', 'Admission Proof'],
    description: 'Merit-cum-means scholarship for West Bengal students pursuing UG/PG courses in STEM, social science, and humanities.',
    officialWebsite: 'https://svmcm.wbhed.gov.in',
    renewable: true,
  },
  {
    id: 'rajasthan-mukhyamantri',
    name: 'Mukhyamantri Ucch Shiksha Scholarship',
    provider: 'Department of College Education, Rajasthan',
    category: 'Need-Based',
    level: 'UG',
    stream: 'All',
    amount: '₹5,000/year',
    eligibility: 'Rajasthan domicile. Min 60% in Class 12. Family income < ₹2.5 LPA. Enrolled in Rajasthan college.',
    applicationPeriod: 'Nov–Dec (every year)',
    selectionCriteria: 'Merit + income criterion',
    documentsRequired: ['Rajasthan Domicile', 'Income Certificate', 'Class 12 Marksheet', 'Aadhaar', 'Enrollment Proof'],
    description: 'State scholarship to help economically weaker students of Rajasthan pursue higher education.',
    officialWebsite: 'https://hte.rajasthan.gov.in',
    renewable: false,
  },

  // ─── Girl Child ──────────────────────────────────────────────────────────
  {
    id: 'pragati-scholarship',
    name: 'AICTE Pragati Scholarship for Girls',
    provider: 'AICTE (All India Council for Technical Education)',
    category: 'Girl Child',
    level: 'UG',
    stream: 'Engineering',
    amount: '₹50,000/year',
    eligibility: 'Female students in AICTE-approved Technical Degree. One girl per family. Family income < ₹8 LPA.',
    applicationPeriod: 'Aug–Oct (every year)',
    selectionCriteria: 'Income criterion; merit in qualifying exam; one per family',
    documentsRequired: ['Income Certificate', 'Aadhaar', 'Admission Letter', 'Bank Account', 'Declaration (single girl)'],
    description: 'Supports female students in technical education by providing financial assistance to promote women in engineering and technology.',
    officialWebsite: 'https://aicte-pragati-saksham-gov.in',
    renewable: true,
    seats: '10,000 per year',
  },
  {
    id: 'saksham-scholarship',
    name: 'AICTE Saksham Scholarship for Differently Abled',
    provider: 'AICTE',
    category: 'Differently Abled',
    level: 'UG',
    stream: 'Engineering',
    amount: '₹50,000/year',
    eligibility: '≥40% permanent disability. Enrolled in AICTE-approved technical degree. Family income < ₹8 LPA.',
    applicationPeriod: 'Aug–Oct (every year)',
    selectionCriteria: 'Disability certificate; income criterion',
    documentsRequired: ['Disability Certificate', 'Income Certificate', 'Aadhaar', 'Admission Proof'],
    description: 'Encourages differently-abled students to pursue technical education by addressing financial barriers.',
    officialWebsite: 'https://aicte-pragati-saksham-gov.in',
    renewable: true,
    seats: '2,000 per year',
  },
  {
    id: 'cbse-merit-scholarship-girls',
    name: 'CBSE Merit Scholarship for Single Girl Child',
    provider: 'Central Board of Secondary Education (CBSE)',
    category: 'Girl Child',
    level: 'UG',
    stream: 'All',
    amount: '₹500/month',
    eligibility: 'Single girl child of parents. Min 60% in Class 10 CBSE. Pursuing Class 11–12 or UG in non-professional course.',
    applicationPeriod: 'Sep–Oct (every year)',
    selectionCriteria: 'Marks in CBSE Class 10; single girl child status',
    documentsRequired: ['Class 10 Marksheet', 'Affidavit (single child)', 'Aadhaar', 'Admission Proof'],
    description: 'Promotes education of the girl child by recognizing merit and supporting single girl children in CBSE board.',
    officialWebsite: 'https://cbse.gov.in',
    renewable: true,
  },

  // ─── Sports ───────────────────────────────────────────────────────────────
  {
    id: 'sports-scholarship-central',
    name: 'National Sports Scholarship',
    provider: 'Ministry of Youth Affairs & Sports, GoI',
    category: 'Sports',
    level: 'Both',
    stream: 'All',
    amount: '₹5,000–₹10,000/month',
    eligibility: 'Outstanding sports performance at national/international level. Age 12–25.',
    applicationPeriod: 'Jul–Sep (every year)',
    selectionCriteria: 'Sports achievements; recommendation from national federation',
    documentsRequired: ['Sports Achievement Certificates', 'Aadhaar', 'Recommendation Letter', 'Bank Account'],
    description: 'Encourages sporting talent by providing financial support to promising athletes to pursue higher education alongside sports.',
    officialWebsite: 'https://yas.nic.in',
    renewable: true,
  },

  // ─── Private/Corporate ────────────────────────────────────────────────────
  {
    id: 'tata-scholarship',
    name: 'Tata Scholarship for Cornell University',
    provider: 'Tata Trusts',
    category: 'Merit',
    level: 'UG',
    stream: 'All',
    amount: 'Up to USD 25,000/year',
    eligibility: 'Indian nationals admitted to Cornell University undergraduate program with demonstrated financial need.',
    applicationPeriod: 'During Cornell admission process',
    selectionCriteria: 'Admission to Cornell; financial need',
    documentsRequired: ['Cornell Admission Offer', 'Financial Need Proof', 'Passport'],
    description: 'Covers tuition and living expenses for Indian students admitted to Cornell University, enabling global higher education opportunities.',
    officialWebsite: 'https://tatatrusts.org',
    renewable: true,
  },
  {
    id: 'reliance-foundation-scholarship',
    name: 'Reliance Foundation UG Scholarship',
    provider: 'Reliance Foundation',
    category: 'Merit',
    level: 'UG',
    stream: 'Engineering',
    amount: '₹2,00,000/year',
    eligibility: 'Indian nationals in 1st year UG at NIRF top-100 institution. Min 60% in Class 12. Family income < ₹15 LPA.',
    applicationPeriod: 'Jul–Sep (every year)',
    selectionCriteria: 'Merit; essay; income; online test',
    documentsRequired: ['Class 12 Marksheet', 'Income Certificate', 'Admission Proof', 'Aadhaar'],
    description: 'Supports bright students from modest backgrounds pursuing undergraduate engineering and technology degrees at top Indian institutions.',
    officialWebsite: 'https://reliancefoundation.org',
    renewable: true,
    seats: '5,000 per year',
  },
  {
    id: 'hdfc-scholarship',
    name: 'HDFC Bank Parivartan\'s ECS Scholarship',
    provider: 'HDFC Bank Ltd',
    category: 'Need-Based',
    level: 'UG',
    stream: 'All',
    amount: '₹75,000/year',
    eligibility: 'Students in UG professional courses. Family income < ₹4.5 LPA. Min 55% in Class 12.',
    applicationPeriod: 'Oct–Dec (every year)',
    selectionCriteria: 'Income criterion; merit; online application',
    documentsRequired: ['Class 12 Marksheet', 'Income Certificate', 'Admission Proof', 'Aadhaar', 'Bank Account'],
    description: 'Supports underprivileged meritorious students pursuing professional UG degrees to realize their full potential.',
    officialWebsite: 'https://www.hdfcbank.com/parivartan',
    renewable: true,
  },
  {
    id: 'aditya-birla-scholarship',
    name: 'Aditya Birla Scholarship',
    provider: 'Aditya Birla Group',
    category: 'Merit',
    level: 'UG',
    stream: 'All',
    amount: '₹65,000/year',
    eligibility: 'Admitted to IITs, BITS Pilani, IIMs, XLRI, or other partner institutions. Top 20 rank in JEE/CAT/XAT.',
    applicationPeriod: 'After admission to partner institutions (Aug–Sep)',
    selectionCriteria: 'Entrance rank; personal interview',
    documentsRequired: ['Entrance Rank Card', 'Admission Proof', 'Aadhaar'],
    description: 'Recognizes academic excellence by supporting bright minds at India\'s premier institutions in engineering, management, and law.',
    officialWebsite: 'https://adityabirlascholars.net',
    renewable: true,
    seats: '60 per year',
  },
  {
    id: 'buddy4study-scholarship',
    name: 'Buddy4Study Education Scholarship',
    provider: 'Buddy4Study India Foundation',
    category: 'Need-Based',
    level: 'Both',
    stream: 'All',
    amount: '₹10,000–₹50,000',
    eligibility: 'Indian students (Class 1 – PG). Family income < ₹6 LPA. Min 50% in last exam.',
    applicationPeriod: 'Rolling basis',
    selectionCriteria: 'Income criterion; merit; profile completeness',
    documentsRequired: ['Income Certificate', 'Last Marksheet', 'Aadhaar', 'Bank Account'],
    description: 'India\'s largest scholarship platform connecting students from all backgrounds with thousands of scholarship programs.',
    officialWebsite: 'https://buddy4study.com',
    renewable: false,
  },
];

export const categoryColors: Record<ScholarshipCategory, string> = {
  'Merit': 'bg-blue-100 text-blue-700',
  'Need-Based': 'bg-green-100 text-green-700',
  'State': 'bg-purple-100 text-purple-700',
  'Minority': 'bg-orange-100 text-orange-700',
  'SC/ST/OBC': 'bg-amber-100 text-amber-700',
  'Sports': 'bg-red-100 text-red-700',
  'Girl Child': 'bg-pink-100 text-pink-700',
  'Differently Abled': 'bg-teal-100 text-teal-700',
};

export const levelColors: Record<ScholarshipLevel, string> = {
  'UG': 'bg-sky-100 text-sky-700',
  'PG': 'bg-violet-100 text-violet-700',
  'Both': 'bg-indigo-100 text-indigo-700',
  'Doctoral': 'bg-rose-100 text-rose-700',
};
